spring.application.name=SmartNotificationManagementSystem

server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# KAFKA

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.admin.auto-create=true
# Consumer
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Required for NotificationMessage deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.smart.notification.management.system.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=com.smart.notification.management.system.kafka.NotificationMessage
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false


# LOGGING
logging.level.root=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO
logging.level.com.smart.notification.management.system=DEBUG

# CUSTOM CONFIG
notification.kafka.topic=notification-topic

notification.retry.max-attempts=3
notification.retry.cooldown-minutes=2

notification.duplicate.window-minutes=5

notification.failure-rate=30